accumulation_steps: 1
answer_weight: 0.1
cache_dir: /home/mkurman/gitlab/ai/hf_cache
dataset_name: open-r1/OpenR1-Math-220k
format_weight: 0.03
grpo_beta: 0.05
learning_rate: 5.0e-07
max_feedback_new_tokens: 4096
max_grad_norm: 0.1
max_new_tokens: 3072
max_seq_length: 4096
num_return_sequences: 4
openai_base_url: https://openrouter.ai/api/v1/
output_dir: /home/mkurman/gitlab/ai/training
save_steps: 50
seed: 3407
sft_beta: 0.05
student_model_name: /home/mkurman/gitlab/ai/model-trainer/results/llama-teacher-learning/2025-02-14
  01_51_40/checkpoint-200
teacher_model_name: deepseek/deepseek-r1-distill-qwen-14b
temperature: 0.7
thought_process_weight: 0.07
top_k: 50
top_p: 0.9
total_steps: 1000
warmup_steps: 100
