openai_base_url: "http://localhost/v1/"
student_model_name: "mkurman/Llama-3.2-MedIT-SUN-2.5B-BT-GRPO"
teacher_model_name: "mkurman/Qwen2.5-14B-DeepSeek-R1-1M"
dataset_name: "open-r1/OpenR1-Math-220k"
output_dir: "~/.models/"
save_steps: 50
learning_rate: 5.0e-07
max_new_tokens: 2048
num_return_sequences: 2
accumulation_steps: 1
temperature: 0.5
top_p: 0.9
top_k: 50
max_seq_length: 4096
warmup_steps: 100
total_steps: 1000
cache_dir: "~/.cache/"
max_grad_norm: 0.1
grpo_beta: 0.05
sft_beta: 0.05
seed: 42
thought_process_weight: 0.07
answer_weight: 0.1
format_weight: 0.03
system_prompt: "Respond in the following format:\n<think>\n...\n</think>\n...\n$\\boxed{answer}$"