use_unsloth: true
load_in_4bit: true
openai_base_url: "http://localhost/v1/"
student_model_name: "mkurman/Llama-3.2-MedIT-SUN-2.5B-BT-GRPO"
teacher_model_name: "mkurman/Qwen2.5-14B-DeepSeek-R1-1M"
dataset_name: "open-r1/OpenR1-Math-220k"
dataset_question_column: "problem"
dataset_answer_column: "answer"
output_dir: "~/.models/"
save_steps: 50
learning_rate: 5.0e-07
max_new_tokens: 2048
max_feedback_new_tokens: 4096
num_return_sequences: 2
accumulation_steps: 1
temperature: 0.5
top_p: 0.9
top_k: 50
max_seq_length: 4096
warmup_steps: 100
total_steps: 1000
cache_dir: "~/.cache/"
max_grad_norm: 0.1
grpo_beta: 0.05
sft_beta: 0.05
seed: 42
thought_process_weight: 0.07
answer_weight: 0.1
format_weight: 0.03
system_prompt: "Respond in the following format:\n<think>\n...\n</think>\n...\n$\\boxed{answer}$"
evaluation_prompt: "You are a teacher evaluating a student's answer. Evaluate the following student's response in two parts:\n1) Correctness of the thought process (rated from 1 to 10), and\n2) Correctness of the final answer (rated from 1 to 10).\n3) Format and clarity of the response (rated from 1 to 10). Student must have <think> and </think> tags included! If not, give 0 points for this assesment.\n\nThink about the student's thought process and the final answer using <think> ... </think> tags.\nProvide detailed feedback after your thinking process using the following XML format:\n<evaluation>\n  <thought_process><score>{score}</score><explanation>{explanation}</thought_process>\n  <answer><score>{score}</score><explanation>{explanation}</answer>\n  <format><score>{score}</score><explanation>{explanation}</format>\n</evaluation>\n\nStudent Response:\n{student_response}\nGround Truth:\n{ground_truth}\n"
think_open_string: "<think>"
think_close_string: "</think>"